FROM python:3.9

WORKDIR /app
COPY requirements.txt /app/
RUN apt-get update && apt-get install -y wait-for-it
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/
EXPOSE 3000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]