# Generated by Django 3.2.25 on 2024-06-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=10)),
                ('requested_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_send', to='user_management.user')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_recieved', to='user_management.user')),
            ],
        ),
    ]
